"""
Export
======
Packages detection outputs into downloadable bytes: annotated images
(PNG), detection tables (CSV/JSON), and a human-readable Markdown
detection report summarizing a session.
"""

from __future__ import annotations

import io
import json
from datetime import datetime, timezone

import numpy as np
import pandas as pd
from PIL import Image


def image_to_bytes(image_rgb: np.ndarray, fmt: str = "PNG") -> bytes:
    """Encode an RGB numpy image to raw bytes in the given format for download."""
    pil_image = Image.fromarray(image_rgb)
    buffer = io.BytesIO()
    pil_image.save(buffer, format=fmt)
    return buffer.getvalue()


def dataframe_to_csv_bytes(df: pd.DataFrame) -> bytes:
    """Encode a detections DataFrame as CSV bytes."""
    return df.to_csv(index=False).encode("utf-8")


def dataframe_to_json_bytes(df: pd.DataFrame) -> bytes:
    """Encode a detections DataFrame as pretty-printed JSON bytes."""
    records = df.to_dict(orient="records")
    return json.dumps(records, indent=2).encode("utf-8")


def generate_markdown_report(
    title: str,
    history_entries: list[dict],
) -> str:
    """Build a human-readable Markdown detection report from session history.

    `history_entries` follows the shape produced by
    `utils.history.log_detection` — a list of dicts with keys like
    `timestamp`, `kind`, `source_name`, `object_count`, `class_counts`, etc.
    """
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    total_runs = len(history_entries)
    total_objects = sum(entry.get("object_count", 0) for entry in history_entries)

    lines = [
        f"# {title}",
        "",
        f"*Generated {generated_at}*",
        "",
        "## Summary",
        "",
        f"- **Total detection runs:** {total_runs}",
        f"- **Total objects detected:** {total_objects}",
        "",
        "## Run Details",
        "",
        "| # | Type | Source | Objects | Model | Timestamp |",
        "|---|------|--------|---------|-------|-----------|",
    ]

    for i, entry in enumerate(history_entries, start=1):
        lines.append(
            f"| {i} | {entry.get('kind', '—')} | {entry.get('source_name', '—')} | "
            f"{entry.get('object_count', 0)} | {entry.get('model', '—')} | "
            f"{entry.get('timestamp', '—')} |"
        )

    lines += [
        "",
        "---",
        "*Report generated by AI Vision Detect Pro — YOLOv8 · OpenCV · Streamlit*",
    ]
    return "\n".join(lines)
